name: Development Tests

on:
  schedule:
    # Run tests every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of tests to run'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - unit
        - integration
        - coverage
        - lint
        - security

jobs:
  dev-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-3.11-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-3.11-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-asyncio pytest-cov pytest-mock
        pip install flake8 black isort mypy bandit safety
    
    - name: Run all tests
      if: github.event.inputs.test_type == 'all' || github.event.inputs.test_type == ''
      run: |
        python -m pytest --cov=meshmind --cov-report=xml --cov-report=term-missing --disable-warnings
    
    - name: Run unit tests only
      if: github.event.inputs.test_type == 'unit'
      run: |
        python -m pytest -m unit --disable-warnings
    
    - name: Run integration tests only
      if: github.event.inputs.test_type == 'integration'
      run: |
        python -m pytest -m integration --disable-warnings
    
    - name: Run coverage report
      if: github.event.inputs.test_type == 'coverage'
      run: |
        python -m pytest --cov=meshmind --cov-report=html --cov-report=term-missing --disable-warnings
    
    - name: Run linting
      if: github.event.inputs.test_type == 'lint'
      run: |
        black --check --diff src/ tests/
        isort --check-only --diff src/ tests/
        flake8 src/ tests/ --max-line-length=88 --extend-ignore=E203,W503
        mypy src/ --ignore-missing-imports --no-strict-optional
    
    - name: Run security checks
      if: github.event.inputs.test_type == 'security'
      run: |
        bandit -r src/ -f json -o bandit-report.json || true
        safety check --json --output safety-report.json || true
    
    - name: Upload coverage artifacts
      if: github.event.inputs.test_type == 'coverage'
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov/
        retention-days: 30
